name: Build Guix Packages
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: apt-get update
        run: |
          sudo apt-get update
      - name: Install guix
        run: |
          sudo apt-get install guix
      - name: Build
        run: |
          guix build -L . my-hello
